### ISSUE TITLE
Lag spikes from Entire System

### ISSUE THREAD

**Issue by 62Storm** [PrinceOfAmber/Storage-Network#280]
Minecraft version & Mod Version:
1.15.2
SimpleStorageNetwork-1.15.2-0.3.2.jar

Single player or Server:
Server

Describe problem (what you were doing / what happened):
Lag ticks from crafting inside simple storage (with both the remote and the network table). Even removing items from simple storage is now causing lag spikes. It's making the entire system unusable on a server. I think this adds on to the issue that SomeAddons reported. 

Crash log (if any):

(If this is a suggestion and not a bug report, delete all this and just write your suggestion!)

**Comment by primeinc** [comment]
I've got this problem with 1.12.2 as well, here is one example. I do have a very large storage network however.

`The server appears to have lag spiked.
Last tick 0.21274269s ago."Server thread" RUNNABLE
at mrriegel.storagenetwork.util.inventory.ItemStackHandlerEx.getStacks(ItemStackHandlerEx.java:16)
at mrriegel.storagenetwork.util.inventory.FilterItemStackHandler.getStackMatchers(FilterItemStackHandler.java:45)
at mrriegel.storagenetwork.util.inventory.FilterItemStackHandler.isStackFiltered(FilterItemStackHandler.java:64)
at mrriegel.storagenetwork.capabilities.CapabilityConnectableLink.extractStack(CapabilityConnectableLink.java:130)
at mrriegel.storagenetwork.block.master.TileMaster.request(TileMaster.java:367)
at mrriegel.storagenetwork.block.master.TileMaster.updateExports(TileMaster.java:331)
at mrriegel.storagenetwork.block.master.TileMaster.func_73660_a(TileMaster.java:508)
at org.spongepowered.common.event.tracking.TrackingUtil.tickTileEntity(TrackingUtil.java:237)
at net.minecraft.world.WorldServer.updateTileEntity(WorldServer.java:4726)
at net.minecraft.world.WorldServer.redirect$zlj000$onUpdateTileEntities(WorldServer.java:4710)
at net.minecraft.world.World.func_72939_s(World.java:1838)
at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:3928)
at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397)
at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
at java.lang.Thread.run(Thread.java:748)`

**Comment by Lothrazar** [comment]
Can i see some screenshots of your network? How many containers do you have connected? What mods are the containers from?  Ive looked at dozens of lag issues and 95% of the time the lag is from the connected container , but can be investigated anyway.

This is why we use mods like sampler to track down the actual source of the lag https://www.curseforge.com/minecraft/mc-mods/sampler/files

**Comment by primeinc** [comment]
I'm not sure I did this right, and also had to restart the server to install Sampler but here is a snapshot I took on the server, right after a server restart it doesn't lag as much so this might not be a great example. [https://drive.google.com/file/d/14N6GtndTuUZIZbIi8XSg6Bovk96vvT8j/view?usp=sharing](url)

I'll get another sample when it gets really bad. Is the /sampler start on the server and /sampler export sufficient or are there other options I should be trying to use to get more information?

Here are some screenshots as well. [https://imgur.com/a/muaI1hX](url)

The only thing I'll mention as well is that while I noticed lag start to be an issue before, it got really bad when trying to setup a fish farm and automatically cooking the fish and exporting them to culinary generators + wireless. Like I said before, it's entirely possible I'm just trying to do too much but I appreciate your willingness to investigate.

Server has 12 GB of ram dedicated to it if that makes a difference. After a restart it usually around 4-5 GB of usage but I've seen it run away like GC isn't working.

**Comment by primeinc** [comment]
I just left the server on and haven't had anyone logged in for hours, as soon as I login I start getting can't keep up messages. Ram usage increased even though nobody was logged in.

[https://drive.google.com/file/d/1nBV7sg1R0pCyD5eiHGjX720muF8wv0hB/view?usp=sharing](url) is the new snapshot. 

```
Server ran the command: /sampler memory
Heap: 2501 / 6258 MB (max. 11185 MB).
Non heap: 309 / 318 MB (max. 0 MB).
Pool direct: 12 buffers using 2 MB (capacity 2 MB).
Pool mapped: 0 buffers using 0 MB (capacity 0 MB).
Classes: 31137, loaded 31165, unloaded 28
MC display lists: 0, threads: 36.
Total: 7181 MB in RAM, 0 MB in SWAP (virtual 20854 MB).
System: RAM 8525 / 15354 MB, SWAP 24 / 12884 MB.
GC PS Scavenge: 1414x in 37859 ms (1801 ppm of uptime).
GC PS MarkSweep: 10x in 10016 ms (476 ppm of uptime).
```

**Comment by shinji257** [comment]
Lag spikes happen anytime someone tries to craft an item in large quantities.  I had at least one server network try to severely hamper how big the network got because of people doing this.
