### ISSUE TITLE
Game crashes when i click on storage sytem

### ISSUE THREAD

**Issue by pat43player** [PrinceOfAmber/Storage-Network#284]
Minecraft version & Mod Version:
1.15.2

Single player or Server:
Single player

Describe problem (what you were doing / what happened):
I installed the mod the other day and everything worked fine, the next day the game crashed when i click on the storage table, the pipes and the storagemaster are fine.

I already tried to reinstall the mod, running it alone and updating my forge version.

Crash log (if any):
 
---- Minecraft Crash Report ----
// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 11.06.20 17:48
Description: Unexpected error

java.lang.NoClassDefFoundError: mezz/jei/api/recipe/IFocus
	at com.lothrazar.storagenetwork.gui.NetworkWidget.initSearchbar(NetworkWidget.java:192) ~[?:1.15.2-0.2.4] {re:classloading}
	at com.lothrazar.storagenetwork.block.request.GuiNetworkTable.init(GuiNetworkTable.java:56) ~[?:1.15.2-0.2.4] {re:classloading}
	at net.minecraft.client.gui.screen.Screen.init(Screen.java:339) ~[?:?] {re:classloading,pl:runtimedistcleaner:A,re:mixin,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_147108_a(Minecraft.java:800) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraftforge.fml.network.FMLPlayMessages$OpenContainer.lambda$null$0(FMLPlayMessages.java:291) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.network.FMLPlayMessages$OpenContainer$$Lambda$5383/612189364.accept(Unknown Source) ~[?:?] {}
	at java.util.Optional.ifPresent(Optional.java:159) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.network.FMLPlayMessages$OpenContainer.lambda$handle$1(FMLPlayMessages.java:286) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.network.FMLPlayMessages$OpenContainer$$Lambda$5382/2078517303.run(Unknown Source) ~[?:?] {}
	at net.minecraftforge.fml.network.NetworkEvent$Context.enqueueWork(NetworkEvent.java:215) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.network.FMLPlayMessages$OpenContainer.handle(FMLPlayMessages.java:284) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.network.NetworkInitialization$$Lambda$2193/630669831.accept(Unknown Source) ~[?:?] {}
	at net.minecraftforge.fml.network.simple.IndexedMessageCodec.lambda$tryDecode$3(IndexedMessageCodec.java:128) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.network.simple.IndexedMessageCodec$$Lambda$4999/1817490315.accept(Unknown Source) ~[?:?] {}
	at java.util.Optional.ifPresent(Optional.java:159) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.network.simple.IndexedMessageCodec.tryDecode(IndexedMessageCodec.java:128) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.network.simple.IndexedMessageCodec.consume(IndexedMessageCodec.java:162) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.network.simple.SimpleChannel.networkEventListener(SimpleChannel.java:80) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.network.simple.SimpleChannel$$Lambda$2138/630537190.accept(Unknown Source) ~[?:?] {}
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:212) ~[eventbus-2.2.0-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:204) ~[eventbus-2.2.0-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus$$Lambda$2140/8039120.invoke(Unknown Source) ~[?:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258) ~[eventbus-2.2.0-service.jar:?] {}
	at net.minecraftforge.fml.network.NetworkInstance.dispatch(NetworkInstance.java:84) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.network.NetworkHooks.lambda$onCustomPayload$1(NetworkHooks.java:78) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.network.NetworkHooks$$Lambda$4986/1021881658.apply(Unknown Source) ~[?:?] {}
	at java.util.Optional.map(Optional.java:215) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.network.NetworkHooks.onCustomPayload(NetworkHooks.java:78) ~[?:?] {re:classloading}
	at net.minecraft.client.network.play.ClientPlayNetHandler.func_147240_a(ClientPlayNetHandler.java:1868) ~[?:?] {re:classloading,xf:fml:xaerominimap:xaero_clientplaynethandler_handlechunkdata,xf:fml:xaerominimap:xaero_clientplaynethandler_handleblockchange,xf:fml:xaerominimap:xaero_clientplaynethandler_handlemultiblockchange,pl:runtimedistcleaner:A}
	at net.minecraft.network.play.server.SCustomPayloadPlayPacket.func_148833_a(SCustomPayloadPlayPacket.java:59) ~[?:?] {re:classloading}
	at net.minecraft.network.play.server.SCustomPayloadPlayPacket.func_148833_a(SCustomPayloadPlayPacket.java:11) ~[?:?] {re:classloading}
	at net.minecraft.network.PacketThreadUtil.lambda$checkThreadAndEnqueue$0(PacketThreadUtil.java:33) ~[?:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.network.PacketThreadUtil$$Lambda$5104/1326395812.run(Unknown Source) ~[?:?] {}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(ThreadTaskExecutor.java:173) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) ~[?:?] {re:classloading}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(ThreadTaskExecutor.java:135) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213160_bf(ThreadTaskExecutor.java:115) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:897) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:553) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(SourceFile:204) [?:?] {re:classloading}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:56) [forge-1.15.2-31.2.0.jar:31.2] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$443/1265287441.call(Unknown Source) [forge-1.15.2-31.2.0.jar:31.2] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-5.1.0.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-5.1.0.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-5.1.0.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-5.1.0.jar:?] {re:classloading}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-5.1.0.jar:?] {re:classloading}
Caused by: java.lang.ClassNotFoundException: mezz.jei.api.recipe.IFocus
	at java.lang.ClassLoader.findClass(ClassLoader.java:530) ~[?:1.8.0_51] {}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_51] {}
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:101) ~[modlauncher-5.1.0.jar:?] {re:classloading}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_51] {}
	... 51 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at com.lothrazar.storagenetwork.gui.NetworkWidget.initSearchbar(NetworkWidget.java:192)
	at com.lothrazar.storagenetwork.block.request.GuiNetworkTable.init(GuiNetworkTable.java:56)
	at net.minecraft.client.gui.screen.Screen.init(Screen.java:339)
	at net.minecraft.client.Minecraft.func_147108_a(Minecraft.java:800)
	at net.minecraftforge.fml.network.FMLPlayMessages$OpenContainer.lambda$null$0(FMLPlayMessages.java:291)
	at net.minecraftforge.fml.network.FMLPlayMessages$OpenContainer$$Lambda$5383/612189364.accept(Unknown Source)
	at java.util.Optional.ifPresent(Optional.java:159)
	at net.minecraftforge.fml.network.FMLPlayMessages$OpenContainer.lambda$handle$1(FMLPlayMessages.java:286)
	at net.minecraftforge.fml.network.FMLPlayMessages$OpenContainer$$Lambda$5382/2078517303.run(Unknown Source)
	at net.minecraftforge.fml.network.NetworkEvent$Context.enqueueWork(NetworkEvent.java:215)
	at net.minecraftforge.fml.network.FMLPlayMessages$OpenContainer.handle(FMLPlayMessages.java:284)
	at net.minecraftforge.fml.network.NetworkInitialization$$Lambda$2193/630669831.accept(Unknown Source)
	at net.minecraftforge.fml.network.simple.IndexedMessageCodec.lambda$tryDecode$3(IndexedMessageCodec.java:128)
	at net.minecraftforge.fml.network.simple.IndexedMessageCodec$$Lambda$4999/1817490315.accept(Unknown Source)
	at java.util.Optional.ifPresent(Optional.java:159)
	at net.minecraftforge.fml.network.simple.IndexedMessageCodec.tryDecode(IndexedMessageCodec.java:128)
	at net.minecraftforge.fml.network.simple.IndexedMessageCodec.consume(IndexedMessageCodec.java:162)
	at net.minecraftforge.fml.network.simple.SimpleChannel.networkEventListener(SimpleChannel.java:80)
	at net.minecraftforge.fml.network.simple.SimpleChannel$$Lambda$2138/630537190.accept(Unknown Source)
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:212)
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:204)
	at net.minecraftforge.eventbus.EventBus$$Lambda$2140/8039120.invoke(Unknown Source)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258)
	at net.minecraftforge.fml.network.NetworkInstance.dispatch(NetworkInstance.java:84)
	at net.minecraftforge.fml.network.NetworkHooks.lambda$onCustomPayload$1(NetworkHooks.java:78)
	at net.minecraftforge.fml.network.NetworkHooks$$Lambda$4986/1021881658.apply(Unknown Source)
	at java.util.Optional.map(Optional.java:215)
	at net.minecraftforge.fml.network.NetworkHooks.onCustomPayload(NetworkHooks.java:78)
	at net.minecraft.client.network.play.ClientPlayNetHandler.func_147240_a(ClientPlayNetHandler.java:1868)
	at net.minecraft.network.play.server.SCustomPayloadPlayPacket.func_148833_a(SCustomPayloadPlayPacket.java:59)
	at net.minecraft.network.play.server.SCustomPayloadPlayPacket.func_148833_a(SCustomPayloadPlayPacket.java:11)
	at net.minecraft.network.PacketThreadUtil.lambda$checkThreadAndEnqueue$0(PacketThreadUtil.java:33)
	at net.minecraft.network.PacketThreadUtil$$Lambda$5104/1326395812.run(Unknown Source)
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(ThreadTaskExecutor.java:173)
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23)
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(ThreadTaskExecutor.java:135)

-- Affected level --
Details:
	All players: 1 total; [ClientPlayerEntity['Pat43player'/32, l='MpServer', x=-742.19, y=69.00, z=83.37]]
	Chunk stats: Client Chunk Cache: 1225, 880
	Level dimension: DimensionType{minecraft:overworld}
	Level name: MpServer
	Level seed: -1678024189485325870
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: {}
	Level spawn location: World: (-854,85,7), Chunk: (at 10,5,7 in -54,0; contains blocks -864,0,0 to -849,255,15), Region: (-2,0; contains chunks -64,0 to -33,31, blocks -1024,0,0 to -513,255,511)
	Level time: 343153 game time, 1 day time
	Known server brands: 
	Level was modded: false
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Server brand: forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.world.ClientWorld.func_72914_a(ClientWorld.java:611)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:1763)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:572)
	at net.minecraft.client.main.Main.main(SourceFile:204)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:56)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$443/1265287441.call(Unknown Source)
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65)

-- System Details --
Details:
	Minecraft Version: 1.15.2
	Minecraft Version ID: 1.15.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 6958503200 bytes (6636 MB) / 8589934592 bytes (8192 MB) up to 8589934592 bytes (8192 MB)
	CPUs: 12
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx8G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 5.1.0+69+master.79f13f7
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/eventbus-2.2.0-service.jar eventbus PLUGINSERVICE 
		/forge-1.15.2-31.2.0.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.15.2-31.2.0.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-2.1.1-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.15.2-31.2.0.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.15.2-31.2.0.jar runtimedistcleaner PLUGINSERVICE 
		/preview_OptiFine_1.15.2_HD_U_G1_pre18.jar OptiFine TRANSFORMATIONSERVICE 
		/forge-1.15.2-31.2.0.jar fml TRANSFORMATIONSERVICE 
		/MixinBootstrap-1.0.3.jar mixinbootstrap TRANSFORMATIONSERVICE 
		/OptiForge-MC1.15.2-0.1.19.jar optiforge TRANSFORMATIONSERVICE 
		/MixinBootstrap-1.0.3.jar mixin PLUGINSERVICE 
		/MixinBootstrap-1.0.3.jar mixinbootstrap PLUGINSERVICE 
	FML: 31.2
	Forge: net.minecraftforge:31.2.0
	FML Language Providers: 
		javafml@31.2
		minecraft@1
	Mod List: 
		forge-1.15.2-31.2.0-client.jar Minecraft {minecraft@1.15.2 DONE}
		OptiForge-MC1.15.2-0.1.19.jar OptiForge {optiforge@0.1.19 DONE}
		Simple-Storage-Network-Mod-1.15.2.jar Simple Storage Network {storagenetwork@1.15.2-0.2.4 DONE}
		forge-1.15.2-31.2.0-universal.jar Forge {forge@31.2.0 DONE}
		invtweaks-1.15.2-2.0.3.jar Inventory Tweaks Reborn {invtweaks@1.15.2-2.0.3 DONE}
		Xaeros_Minimap_20.11.0_Forge_1.15.2.jar Xaero's Minimap {xaerominimap@20.11.0 DONE}
		Waystones_1.15.2-6.0.1.jar Waystones {waystones@6.0.1 DONE}
		Project+MMO-1.15-3.1.jar Project MMO {pmmo@3.1 DONE}
		XaerosWorldMap_1.5.7_Forge_1.15.2.jar Xaero's World Map {xaeroworldmap@1.5.7 DONE}
		moreoverlays-1.16.1.jar More Overlays {moreoverlays@1.16.1 DONE}
		ironchest-1.15.2-10.0.3.jar Iron Chests {ironchest@1.15.2-10.0.1 DONE}
		xptome-1.15.2-v1.1.5.jar XP Tome {xpbook@v1.1.5 DONE}
	Launched Version: 1.15.2-forge-31.2.0
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: GeForce GTX 1660/PCIe/SSE2 GL version 4.6.0 NVIDIA 446.14, NVIDIA Corporation
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	Resource Packs: vanilla, file/VanillaBDcraft 128x MC115.zip
	Current Language: Deutsch (Deutschland)
	CPU: 12x AMD Ryzen 5 2600 Six-Core Processor 
	OptiFine Version: OptiFine_1.15.2_HD_U_G1_pre18
	OptiFine Build: 20200519-182630
	Render Distance Chunks: 15
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 446.14
	OpenGlRenderer: GeForce GTX 1660/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 12

(If this is a suggestion and not a bug report, delete all this and just write your suggestion!)

**Comment by Lothrazar** [comment]
do you have JEI installed? if so what version? I am testing right now with newest forge and JEI jei-1.15.2-6.0.2.9.jar

**Comment by Lothrazar** [comment]
added a trycatch, and confirmed it works on latest JEI  6.0.2.12 https://www.curseforge.com/minecraft/mc-mods/simple-storage-network/files/2990699
