### ISSUE TITLE
Error Executing Task - 1.12.2

### ISSUE THREAD

**Issue by Rynslet** [PrinceOfAmber/Storage-Network#318]
**Minecraft version & Mod Version:** 
Minecraft: 1.12.2 
Mod Versions: 1.7.11, 1.7.10, 1.7.8

**Single player or Server:**
Single Player

**Describe problem (what you were doing / what happened):**
Unable to access Storage Request Terminal and three remotes.

**Crash log (if any):**
None

--

Hello. I'm running a modified version of FTB Continuum, minecraft version 1.12.2, and I added this mod to it.

I started with version 1.7.8 (Because that was the version I already had downloaded from Sky Factory 4). I crafted the Storage Request Terminal and Storage Network Master and a few Storage Link Cables. I put them how I liked them, then I tried accessing the Request Terminal and got this error:

[11:48:04] [Server thread/FATAL] [minecraft/MinecraftServer]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NoSuchFieldError: useNormalTransfer
	at java.util.concurrent.FutureTask.report(Unknown Source) ~[?:1.8.0_251]
	at java.util.concurrent.FutureTask.get(Unknown Source) ~[?:1.8.0_251]
	at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185) [chd.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_251]
Caused by: java.lang.NoSuchFieldError: useNormalTransfer
	at mrriegel.storagenetwork.gui.fb.ContainerFastNetworkCrafter.<init>(ContainerFastNetworkCrafter.java:42) ~[ContainerFastNetworkCrafter.class:?]
	at mrriegel.storagenetwork.gui.fb.ContainerFastRequest.<init>(ContainerFastRequest.java:24) ~[ContainerFastRequest.class:?]
	at mrriegel.storagenetwork.gui.GuiHandler.getServerGuiElement(GuiHandler.java:66) ~[GuiHandler.class:?]
	at net.minecraftforge.fml.common.network.NetworkRegistry.getRemoteGuiContainer(NetworkRegistry.java:253) ~[NetworkRegistry.class:?]
	at net.minecraftforge.fml.common.network.internal.FMLNetworkHandler.openGui(FMLNetworkHandler.java:88) ~[FMLNetworkHandler.class:?]
	at net.minecraft.entity.player.EntityPlayer.openGui(EntityPlayer.java:2550) ~[aed.class:?]
	at mrriegel.storagenetwork.block.request.BlockRequest.func_180639_a(BlockRequest.java:82) ~[BlockRequest.class:?]
	at net.minecraft.server.management.PlayerInteractionManager.func_187251_a(PlayerInteractionManager.java:449) ~[or.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_184337_a(NetHandlerPlayServer.java:741) ~[pa.class:?]
	at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(SourceFile:55) ~[ma.class:?]
	at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(SourceFile:11) ~[ma.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[hv$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_251]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_251]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
	... 5 more

This error does not crash the game. But right clicking again on the Request Table again throws this error. At this point I figured I'd update the mod. I tried 1.7.11 and 1.7.10 with identical results. Only one of the four remotes, the "Simple Storage Remote", work, as well. The rest produce the same error when used.

I do not know what mod is conflicting with Simple Storage Network to make this happen, but I know it is something within a vanilla Continuum save, as I just tried it myself. 

Vaniila Continuum Mod List: https://pastebin.com/R9Z8DZtd
My modified modlist: https://pastebin.com/j5tcPUFK

Thank you for your time.

**Comment by Lothrazar** [comment]
use a newer version of fast workbench - such as 1.7.3 . or disable it with config

 B:allowFastWorkBenchIntegration=false
