### ISSUE TITLE
1.16.4 Ticking block entity crash

### ISSUE THREAD

**Issue by mnsnownutt** [PrinceOfAmber/Storage-Network#336]
Minecraft version & Mod Version: 1.16.4, 1.3.1

Single player or Server: Single player (luckily, running a test in creative before implementing)

Describe problem (what you were doing / what happened):  placed a network interface link on a network exchange.  No other blocks or entities were placed in the test world.
[crash-2021-01-22_08.56.49-server.txt](https://github.com/Lothrazar/Storage-Network/files/5856636/crash-2021-01-22_08.56.49-server.txt)

Crash log (if any):

https://user-images.githubusercontent.com/31514693/105507920-62a62100-5c91-11eb-81bf-ab7e3d3b6161.mp4

(If this is a suggestion and not a bug report, delete all this and just write your suggestion!)

**Comment by Lothrazar** [comment]
`
java.lang.NullPointerException: Ticking block entity
	at com.lothrazar.storagenetwork.block.exchange.TileExchange.getCapability(TileExchange.java:45) ~[storagenetwork:1.16.4-1.3.1] {re:classloading}
	at com.lothrazar.storagenetwork.block.TileCableWithFacing.isValidLinkNeighbor(TileCableWithFacing.java:47) ~[storagenetwork:1.16.4-1.3.1] {re:classloading}
	at com.lothrazar.storagenetwork.block.TileCableWithFacing.findNewDirection(TileCableWithFacing.java:58) ~[storagenetwork:1.16.4-1.3.1] {re:classloading}
	at com.lothrazar.storagenetwork.block.TileCableWithFacing.refreshDirection(TileCableWithFacing.java:90) ~[storagenetwork:1.16.4-1.3.1] {re:classloading}
	at com.lothrazar.storagenetwork.block.cable.link.TileCableLink.func_73660_a(TileCableLink.java:55) ~[storagenetwork:1.16.4-1.3.1] {re:classloading}`

**Comment by Lothrazar** [comment]
Fix coming soon 1.3.2
