### ISSUE TITLE
Storage request table not working/working without the crafting table

### ISSUE THREAD

**Issue by JustaMikie** [PrinceOfAmber/Storage-Network#354]
Minecraft version & Mod Version:
MC 1.12.2 & mod is 1.8.1

Single player or Server:
Server

Describe problem (what you were doing / what happened):
I just wanted to make a storage req. table, I connected it and everything, but when I click on it, nothing happens, it works with a remote thing, but without the crafting table, it just isn't there

Crash log (if any):

https://pastebin.com/bHhQ8DtJ

If you scroll all the way down you can see the same error repeating

**Comment by Lothrazar** [comment]
java.util.concurrent.ExecutionException: java.lang.NoSuchMethodError: shadows.fastbench.gui.ContainerFastBench.<init>(Lnet/minecraft/entity/player/EntityPlayer;Lnet/minecraft/world/World;Lnet/minecraft/util/math/BlockPos;)V
	at java.util.concurrent.FutureTask.report(Unknown Source) ~[?:1.8.0_251]
	at java.util.concurrent.FutureTask.get(Unknown Source) ~[?:1.8.0_251]
	at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_251]
Caused by: java.lang.NoSuchMethodError: shadows.fastbench.gui.ContainerFastBench.<init>(Lnet/minecraft/entity/player/EntityPlayer;Lnet/minecraft/world/World;Lnet/minecraft/util/math/BlockPos;)V


You need to udpate "fast workbench" to the latest version, or uninstall it. mod compatibility

**Comment by JustaMikie** [comment]
> java.util.concurrent.ExecutionException: java.lang.NoSuchMethodError: shadows.fastbench.gui.ContainerFastBench.(Lnet/minecraft/entity/player/EntityPlayer;Lnet/minecraft/world/World;Lnet/minecraft/util/math/BlockPos;)V
> at java.util.concurrent.FutureTask.report(Unknown Source) ~[?:1.8.0_251]
> at java.util.concurrent.FutureTask.get(Unknown Source) ~[?:1.8.0_251]
> at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
> at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723) [MinecraftServer.class:?]
> at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?]
> at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
> at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
> at java.lang.Thread.run(Unknown Source) [?:1.8.0_251]
> Caused by: java.lang.NoSuchMethodError: shadows.fastbench.gui.ContainerFastBench.(Lnet/minecraft/entity/player/EntityPlayer;Lnet/minecraft/world/World;Lnet/minecraft/util/math/BlockPos;)V
> 
> You need to udpate "fast workbench" to the latest version, or uninstall it. mod compatibility

Hello, THANG YOU VERY MUCH! It's fixed now! Than you again!
