### ISSUE TITLE
java.lang.OutOfMemoryError: Requested array size exceeds VM limit

### ISSUE THREAD

**Issue by guipleys20** [PrinceOfAmber/Storage-Network#368]
Minecraft version & Mod Version: 1.15.2/SimpleStorageNetwork-1.15.2-1.0.2.jar

Single player or Server: Single Player

Describe problem (what you were doing / what happened): Whenever I place the Storage Network Master, the game crashes.

Crash log (if any): ---- Minecraft Crash Report ----
// There are four lights!

Time: 5/2/21 7:57 PM
Description: Exception in server tick loop

java.lang.OutOfMemoryError: Requested array size exceeds VM limit
	at net.minecraft.util.NonNullList.func_191197_a(SourceFile:21) ~[?:?] {re:classloading}
	at net.minecraftforge.items.ItemStackHandler.<init>(ItemStackHandler.java:42) ~[?:?] {re:classloading}
	at com.lothrazar.storagenetwork.capability.handler.ItemStackHandlerEx.<init>(ItemStackHandlerEx.java:11) ~[?:1.15.2-1.0.2] {re:classloading}
	at com.lothrazar.storagenetwork.capability.handler.MasterItemStackHandler.<init>(MasterItemStackHandler.java:23) ~[?:1.15.2-1.0.2] {re:classloading}
	at com.lothrazar.storagenetwork.capability.handler.MasterItemStackHandler.<init>(MasterItemStackHandler.java:19) ~[?:1.15.2-1.0.2] {re:classloading}
	at com.lothrazar.storagenetwork.block.main.TileMain.<init>(TileMain.java:59) ~[?:1.15.2-1.0.2] {re:classloading}
	at com.lothrazar.storagenetwork.block.main.BlockMain.createTileEntity(BlockMain.java:93) ~[?:1.15.2-1.0.2] {re:classloading}
	at net.minecraftforge.common.extensions.IForgeBlockState.createTileEntity(IForgeBlockState.java:130) ~[?:?] {re:mixin,re:classloading}
	at net.minecraft.world.chunk.Chunk.func_177436_a(Chunk.java:288) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:phosphor.mixins.json:chunk.MixinChunk,pl:mixin:A}
	at net.minecraft.world.World.func_180501_a(World.java:177) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:create.mixins.json:TileWorldHookMixin,pl:mixin:A}
	at net.minecraft.item.BlockItem.func_195941_b(BlockItem.java:146) ~[?:?] {re:classloading,xf:fml:quark:alter-placement-state}
	at net.minecraft.item.BlockItem.func_195942_a(BlockItem.java:54) ~[?:?] {re:classloading,xf:fml:quark:alter-placement-state}
	at net.minecraft.item.BlockItem.func_195939_a(BlockItem.java:39) ~[?:?] {re:classloading,xf:fml:quark:alter-placement-state}
	at net.minecraftforge.common.ForgeHooks.onPlaceItemIntoWorld(ForgeHooks.java:611) ~[?:?] {re:classloading}
	at net.minecraft.item.ItemStack.func_196084_a(ItemStack.java:167) ~[?:?] {re:classloading,xf:fml:quark:add-spacing-for-stack}
	at net.minecraft.server.management.PlayerInteractionManager.func_219441_a(PlayerInteractionManager.java:344) ~[?:?] {re:classloading}
	at net.minecraft.network.play.ServerPlayNetHandler.func_184337_a(ServerPlayNetHandler.java:853) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:fml:randompatches:RandomPatches ServerPlayNetHandler Transformer}
	at net.minecraft.network.play.client.CPlayerTryUseItemOnBlockPacket.func_148833_a(SourceFile:36) ~[?:?] {re:classloading}
	at net.minecraft.network.play.client.CPlayerTryUseItemOnBlockPacket.func_148833_a(SourceFile:10) ~[?:?] {re:classloading}
	at net.minecraft.network.PacketThreadUtil.func_225383_a(SourceFile:21) ~[?:?] {re:classloading}
	at net.minecraft.network.PacketThreadUtil$$Lambda$12067/1401080569.run(Unknown Source) ~[?:?] {}
	at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18) ~[?:?] {re:classloading}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) ~[?:?] {re:mixin,re:classloading}
	at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:731) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:141) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:714) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:708) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213161_c(SourceFile:127) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_213202_o(MinecraftServer.java:694) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:641) ~[?:?] {re:classloading,pl:accesstransformer:B}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.15.2
	Minecraft Version ID: 1.15.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1959348080 bytes (1868 MB) / 3289907200 bytes (3137 MB) up to 5726797824 bytes (5461 MB)
	CPUs: 8
	JVM Flags: 5 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx6144m -Xms256m -XX:PermSize=256m
	ModLauncher: 5.1.2+70+master.2845bb9
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.2.jar mixin PLUGINSERVICE 
		/eventbus-2.2.1-service.jar eventbus PLUGINSERVICE 
		/forge-1.15.2-31.2.50.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.15.2-31.2.50.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-2.1.3-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.15.2-31.2.50.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.15.2-31.2.50.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.2.jar mixin TRANSFORMATIONSERVICE 
		/forge-1.15.2-31.2.50.jar fml TRANSFORMATIONSERVICE 
		/MixinBootstrap-1.0.5.jar mixinbootstrap TRANSFORMATIONSERVICE 
	FML: 31.2
	Forge: net.minecraftforge:31.2.50
	FML Language Providers: 
		javafml@31.2
		minecraft@1
		kotlinforforge@1.11.1
	Mod List: 
		CyclopsCore-1.15.2-1.9.0.jar Cyclops Core {cyclopscore@1.9.0 DONE}
		ClientTweaks_1.15.2-4.2.0.jar Client Tweaks {clienttweaks@4.2.0 DONE}
		Cucumber-1.15.2-3.0.9.jar Cucumber Library {cucumber@3.0.9 DONE}
		NetherPortalFix_1.15.2-6.0.2.jar NetherPortalFix {netherportalfix@6.0.2 DONE}
		jei-1.15.2-6.0.3.16.jar Just Enough Items {jei@6.0.3.16 DONE}
		futuremc-1.15.2-1.1.0.jar Future MC {futuremc@1.15.2-1.1.0 DONE}
		AttributeFix-1.15.2-7.0.2.jar AttributeFix {attributefix@7.0.2 DONE}
		ProjectE-1.15.2-PE1.0.4.jar ProjectE {projecte@1.0.4 DONE}
		Mekanism-1.15.2-9.10.9.422.jar Mekanism {mekanism@9.10.9 DONE}
		caelus-FORGE-1.15.2-2.0-beta4.jar Caelus API {caelus@FORGE-1.15.2-2.0-beta4 DONE}
		KleeSlabs_1.15.2-8.0.0.jar KleeSlabs {kleeslabs@8.0.0 DONE}
		create-mc1.15.2_v0.3.1a.jar Create {create@mc1.15.2_v0.3.1a+478 DONE}
		Clumps-5.0.2.7.jar Clumps {clumps@5.0.2.7 DONE}
		journeymap-1.15.2-5.7.0.jar Journeymap {journeymap@5.7.0 DONE}
		CTM-MC1.15.2-1.1.2.14.jar ConnectedTexturesMod {ctm@MC1.15.2-1.1.2.14 DONE}
		Controlling-6.1.5.6.jar Controlling {controlling@6.1.5.6 DONE}
		ReAuth-1.14-1.15-3.8.1.jar ReAuth {reauth@3.8.1 DONE}
		Placebo-1.15.2-3.1.0.jar Placebo {placebo@3.1.0 DONE}
		SimpleStorageNetwork-1.15.2-1.0.2.jar Simple Storage Network {storagenetwork@1.15.2-1.0.2 DONE}
		BasicNetherOres-1.15.2-4.0.3.jar Basic Nether Ores {bno@4.0.3 DONE}
		Bookshelf-1.15.2-5.6.40.jar Bookshelf {bookshelf@5.6.40 DONE}
		BotanyPots-1.15.2-2.0.29.jar BotanyPots {botanypots@2.0.29 DONE}
		u_team_core-1.15.2-3.0.2.169.jar U Team Core {uteamcore@3.0.2.169 DONE}
		randompatches-1.15.2-1.22.1.1.jar RandomPatches {randompatches@1.15.2-1.22.1.1 DONE}
		DarkUtilities-1.15.2-3.1.9.jar Dark Utilities {darkutils@3.1.9 DONE}
		Morpheus-1.15.2-4.2.50.jar Morpheus {morpheus@version DONE}
		MekanismGenerators-1.15.2-9.10.9.422.jar Mekanism: Generators {mekanismgenerators@9.10.9 DONE}
		Hwyla-forge-1.10.8-B72_1.15.2.jar Waila {waila@version DONE}
		WAWLA-1.15.2-3.0.4.jar WAWLA {wawla@3.0.4 DONE}
		ToastControl-1.15.2-3.0.1.jar Toast Control {toastcontrol@3.0.1 DONE}
		JEITweaker-1.15.2-1.0.1.3.jar JEI Tweaker {jeitweaker@1.0.1.3 DONE}
		carryon-1.15.2-1.13.0.5.jar Carry On {carryon@1.13.0.5 DONE}
		JustEnoughResources-1.15.2-0.10.1.77.jar Just Enough Resources {jeresources@0.10.1.77 DONE}
		CraftTweaker-1.15.2-6.0.0.24.jar CraftTweaker {crafttweaker@6.0.0.24 DONE}
		forge-1.15.2-31.2.50-universal.jar Forge {forge@31.2.50 DONE}
		MysticalAgradditions-1.15.2-3.0.1.jar Mystical Agradditions {mysticalagradditions@3.0.1 DONE}
		MysticalAgriculture-1.15.2-3.0.10.jar Mystical Agriculture {mysticalagriculture@3.0.10 DONE}
		ironchest-1.15.2-10.0.3.jar Iron Chests {ironchest@1.15.2-10.0.1 DONE}
		CraftingTweaks_1.15.2-11.0.1.jar Crafting Tweaks {craftingtweaks@11.0.1 DONE}
		forge-1.15.2-31.2.50-client.jar Minecraft {minecraft@1.15.2 DONE}
		cofh_core-1.15.2-1.0.2.jar CoFH Core {cofh_core@1.0.2 DONE}
		thermal-1.15.2-1.0.2.jar Thermal Series {thermal@1.0.2 DONE}
		industrial-foregoing-1.15.2-2.3.3-e356e61.jar Industrial Foregoing {industrialforegoing@2.3.3 DONE}
		torchmaster-2.2.2.jar Torchmaster {torchmaster@2.2.2 DONE}
		EnchantmentDescriptions-1.15.2-2.0.9.jar EnchantmentDescriptions {enchdesc@2.0.9 DONE}
		CommonCapabilities-1.15.2-2.5.4.jar CommonCapabilities {commoncapabilities@2.5.4 DONE}
		MouseTweaks-2.13-mc1.15.1.jar Mouse Tweaks {mousetweaks@2.13 DONE}
		ToolBelt-1.15.2-1.14.2.jar Tool Belt {toolbelt@1.14.2 DONE}
		titanium-1.15.2-2.4.2.jar Titanium {titanium@2.4.2 DONE}
		ImmersiveEngineering-1.15.2-4.1.1-125.jar Immersive Engineering {immersiveengineering@1.15.2-4.1.1-125 DONE}
		phosphor-forge-mc1.15.2-0.5.2+build.4.jar Phosphor {phosphor@0.5.2+build.4 DONE}
		MekanismAdditions-1.15.2-9.10.9.422.jar Mekanism: Additions {mekanismadditions@9.10.9 DONE}
		easy_villagers-1.15.2-1.0.1.jar Easy Villagers {easy_villagers@1.15.2-1.0.1 DONE}
		curios-FORGE-1.15.2-2.0.2.7.jar Curios API {curios@FORGE-1.15.2-2.0.2.7 DONE}
		collective-1.15.2-2.26.jar Collective {collective@2.26 DONE}
		FastWorkbench-1.15.2-3.1.1.jar FastWorkbench {fastbench@3.1.1 DONE}
		AutoRegLib-1.5-40.jar AutoRegLib {autoreglib@1.5-40 DONE}
		Quark-r2.1-245.jar Quark {quark@r2.1-245 DONE}
		StorageDrawers-1.15.2-7.0.3.jar Storage Drawers {storagedrawers@1.15.2-7.0.3 DONE}
		OreExcavation-1.7.151.jar Ore Excavation {oreexcavation@NONE DONE}
		thermal_expansion-1.15.2-1.0.2.jar Thermal Expansion {thermal_expansion@1.0.2 DONE}
		MysticalCustomization-1.15.2-1.0.0.jar Mystical Customization {mysticalcustomization@1.0.0 DONE}
		elevatorid-1.15.2-1.7.1.jar Elevator Mod {elevatorid@1.15.2-1.7.1 DONE}
		starterkit_1.15.2-2.4.jar Starter Kit {starterkit@2.4 DONE}
		MekanismTools-1.15.2-9.10.9.422.jar Mekanism: Tools {mekanismtools@9.10.9 DONE}
		FastFurnace-1.15.1-3.0.0.jar FastFurnace {fastfurnace@3.0.0 DONE}
		AppleSkin-mc1.15.2-forge-1.0.14.jar AppleSkin {appleskin@1.0.14 DONE}
		curiouselytra-FORGE-1.15.2-2.0.jar Curious Elytra {curiouselytra@FORGE-1.15.2-2.0 DONE}
		AI-Improvements-1.15.2-0.3.0.jar AI-Improvements {aiimprovements@0.3.0 DONE}
		FastLeafDecay-v22.1.jar FastLeafDecay {fastleafdecay@v22.1 DONE}
		CosmeticArmorReworked-1.15.2-v3a.jar CosmeticArmorReworked {cosmeticarmorreworked@1.15.2-v3a DONE}
		CodeChickenLib-1.15.2-3.3.5.407-universal.jar CodeChicken Lib {codechickenlib@3.3.5.407 DONE}
		EnderStorage-1.15.2-2.5.2.164-universal.jar EnderStorage {enderstorage@2.5.2.164 DONE}
		NetherEx-1.15.2-4.0.1.jar NetherEx {netherex@4.0.1 DONE}
		LibraryEx-1.15.2-3.0.1.jar LibraryEx {libraryex@3.0.1 DONE}
		WailaHarvestability-mc1.15.2-1.1.12.jar Waila Harvestability {wailaharvestability@1.1.12 DONE}
		DefaultOptions_1.15.2-11.0.1.jar Default Options {defaultoptions@11.0.1 DONE}
		BetterAdvancements-1.15.2-0.1.0.99.jar Better Advancements {betteradvancements@0.1.0.99 DONE}
	Player Count: 1 / 8; [ServerPlayerEntity['GuiPleys20'/239, l='Teste', x=242.50, y=73.00, z=-107.50]]
	Data Packs: netherex:netherex_nether_biome_pack (incompatible), netherex:enb_nether_biome_pack (incompatible), netherex:default_nether_biome_pack (incompatible), netherex:byg_nether_biome_pack (incompatible), netherex:bop_nether_biome_pack (incompatible), vanilla, mod:cyclopscore (incompatible), mod:clienttweaks (incompatible), mod:cucumber, mod:netherportalfix (incompatible), mod:jei (incompatible), mod:futuremc (incompatible), mod:attributefix (incompatible), mod:projecte, mod:mekanism, mod:caelus (incompatible), mod:kleeslabs (incompatible), mod:create, mod:clumps (incompatible), mod:journeymap (incompatible), mod:ctm, mod:controlling (incompatible), mod:reauth (incompatible), mod:placebo (incompatible), mod:storagenetwork (incompatible), mod:bno (incompatible), mod:bookshelf (incompatible), mod:botanypots (incompatible), mod:uteamcore, mod:randompatches (incompatible), mod:darkutils (incompatible), mod:morpheus (incompatible), mod:mekanismgenerators, mod:waila (incompatible), mod:wawla (incompatible), mod:toastcontrol (incompatible), mod:jeitweaker, mod:carryon (incompatible), mod:jeresources (incompatible), mod:crafttweaker (incompatible), mod:forge (incompatible), mod:mysticalagradditions, mod:mysticalagriculture, mod:ironchest, mod:craftingtweaks (incompatible), mod:cofh_core (incompatible), mod:thermal (incompatible), mod:industrialforegoing (incompatible), mod:torchmaster (incompatible), mod:enchdesc (incompatible), mod:commoncapabilities (incompatible), mod:mousetweaks (incompatible), mod:toolbelt (incompatible), mod:titanium (incompatible), mod:immersiveengineering (incompatible), mod:phosphor, mod:mekanismadditions, mod:easy_villagers, mod:curios (incompatible), mod:collective (incompatible), mod:fastbench (incompatible), mod:autoreglib (incompatible), mod:quark, mod:storagedrawers (incompatible), mod:oreexcavation (incompatible), mod:thermal_expansion (incompatible), mod:mysticalcustomization, mod:elevatorid, mod:starterkit, mod:mekanismtools, mod:fastfurnace (incompatible), mod:appleskin (incompatible), mod:curiouselytra (incompatible), mod:aiimprovements (incompatible), mod:fastleafdecay, mod:cosmeticarmorreworked (incompatible), mod:codechickenlib (incompatible), mod:enderstorage (incompatible), mod:netherex (incompatible), mod:libraryex (incompatible), mod:wailaharvestability (incompatible), mod:defaultoptions (incompatible), mod:betteradvancements (incompatible)
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'forge'

**Comment by iHeartZigg** [comment]
Having the same issue here, although there are more variables I need to test. 
I'll be updating shortly with more info.

Edit: Well, I can't find anything that affects it. 
Crashing even on a fresh world just by placing the block.

[Here's a pastebin link to my crashlog.](https://pastebin.com/10azafRG)
This is on the "Plunger" modpack on Curseforge.
Minecraft version 1.15.2 with the latest update of your mod.

Edit 2: Downgraded to version 1.0.1 and it works just fine.

**Comment by AlexGagne** [comment]
I can confirm the exact same error. Version 1.0.2 for 1.15.2 has the error, but downgrading to 1.0.1 fixes it
