### ISSUE TITLE
Payload may not be larger than 32767 bytes

### ISSUE THREAD

**Issue by tfox83** [PrinceOfAmber/Storage-Network#38]
Simple storage network 1.12.1-1.1.0  

(I have udpated to 1.1.1 in Horizons 1.1.0+, forgive me if this has been fixed in your latest, however I am not able to reproduce this players bug in my testing env) -tfox

"When auto inserting items from jei recipe for things you are missing part of the items in a "simple storage network" a Internal exception: java.langIllefalArgumentException: payload over 32767 creates and error kicking you from server. "

Log: http://paste.feed-the-beast.com/view/4cc5bd3c 
Original Issue Report: https://forum.feed-the-beast.com/threads/payload-may-not-be-larger-than-32767-bytes.260983/

**Comment by BioPrince** [comment]
Another player had the issue when inserting recipes with glass.

**Comment by LupusNoctis** [comment]
Confirming this issue still happening with SSN 1.1.1  included in the Horz3 1.1.0 stable release pack from Twitch Launcher.

**Comment by ftog-thorgal** [comment]
I can confirm this problem in version 1.12.1-1.1.1
`[Netty Client IO #9/ERROR] [FML]: NetworkDispatcher exception
java.lang.IllegalArgumentException: Payload may not be larger than 32767 bytes
	at net.minecraft.network.play.client.CPacketCustomPayload.<init>(CPacketCustomPayload.java:28) ~[lh.class:?]
	at net.minecraftforge.fml.common.network.internal.FMLProxyPacket.toC17Packet(FMLProxyPacket.java:142) ~[FMLProxyPacket.class:?]
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.write(NetworkDispatcher.java:534) ~[NetworkDispatcher.class:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738) ~[AbstractChannelHandlerContext.class:4.1.9.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:801) ~[AbstractChannelHandlerContext.class:4.1.9.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:814) ~[AbstractChannelHandlerContext.class:4.1.9.Final]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:794) ~[AbstractChannelHandlerContext.class:4.1.9.Final]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:831) ~[AbstractChannelHandlerContext.class:4.1.9.Final]
	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1032) ~[DefaultChannelPipeline.class:4.1.9.Final]
	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:296) ~[AbstractChannel.class:4.1.9.Final]
	at net.minecraft.network.NetworkManager$4.run(NetworkManager.java:245) [gw$4.class:?]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) [AbstractEventExecutor.class:4.1.9.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403) [SingleThreadEventExecutor.class:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:442) [NioEventLoop.class:4.1.9.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) [SingleThreadEventExecutor$5.class:4.1.9.Final]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_151]`

**Comment by PrinceOfAmber** [comment]
Sorry ive been away so long. I have a fix for this in-dev, but theres a similar issue im trying to fix as well when i shift-click crafting lots of items from a large network. once both are fixed im putting out a new  public build

Changelog on build so far is here https://github.com/PrinceOfAmber/Storage-Network/pull/45/files#diff-2103efac9db966ed8688bc9b541c1638R45

**Comment by PrinceOfAmber** [comment]
Fixed in latest version 👍
