### ISSUE TITLE
Crash on 1.18

### ISSUE THREAD

**Issue by p3lim** [PrinceOfAmber/Storage-Network#418]
- Minecraft Version: **1.18.1**  
- Forge Version: **39.0.45**  
- Mod Version: **1.18.1-1.5.2**  
- Single Player or Server: **SSP**

#### Describe problem (what you were doing; what happened; what should have happened):

I placed down a Storage Network Root in a completely new world and the game crashed.

#### Relevant logs:

```
[Server thread/ERROR]: Encountered an unexpected exception
java.lang.NoSuchMethodError: 'net.minecraft.nbt.CompoundTag com.lothrazar.storagenetwork.block.main.TileMain.save(net.minecraft.nbt.CompoundTag)'
	at com.lothrazar.storagenetwork.block.main.TileMain.m_5995_(TileMain.java:146) ~[SimpleStorageNetwork-1.18.1-1.5.2.jar%23109!/:1.18.1-1.5.2]
	at net.minecraft.network.protocol.game.ClientboundLevelChunkPacketData$BlockEntityInfo.m_195691_(ClientboundLevelChunkPacketData.java:153) ~[client-1.18.1-20211210.034407-srg.jar%23121!/:?]
	at net.minecraft.network.protocol.game.ClientboundLevelChunkPacketData.<init>(ClientboundLevelChunkPacketData.java:44) ~[client-1.18.1-20211210.034407-srg.jar%23121!/:?]
	at net.minecraft.network.protocol.game.ClientboundLevelChunkWithLightPacket.<init>(ClientboundLevelChunkWithLightPacket.java:24) ~[client-1.18.1-20211210.034407-srg.jar%23121!/:?]
	at net.minecraft.server.level.ChunkMap.m_183760_(ChunkMap.java:1125) ~[client-1.18.1-20211210.034407-srg.jar%23121!/:?]
	at net.minecraft.server.level.ChunkMap.m_183754_(ChunkMap.java:785) ~[client-1.18.1-20211210.034407-srg.jar%23121!/:?]
	at net.minecraft.server.level.ChunkMap.m_140192_(ChunkMap.java:923) ~[client-1.18.1-20211210.034407-srg.jar%23121!/:?]
	at net.minecraft.server.level.ChunkMap.m_140199_(ChunkMap.java:1045) ~[client-1.18.1-20211210.034407-srg.jar%23121!/:?]
	at net.minecraft.server.level.ServerChunkCache.m_8463_(ServerChunkCache.java:458) ~[client-1.18.1-20211210.034407-srg.jar%23121!/:?]
	at net.minecraft.server.level.ServerLevel$EntityCallbacks.m_141985_(ServerLevel.java:1551) ~[client-1.18.1-20211210.034407-srg.jar%23121!/:?]
	at net.minecraft.server.level.ServerLevel$EntityCallbacks.m_141985_(ServerLevel.java:1534) ~[client-1.18.1-20211210.034407-srg.jar%23121!/:?]
	at net.minecraft.world.level.entity.PersistentEntitySectionManager.m_157575_(PersistentEntitySectionManager.java:135) ~[client-1.18.1-20211210.034407-srg.jar%23121!/:?]
	at net.minecraft.world.level.entity.PersistentEntitySectionManager.addEntityWithoutEvent(PersistentEntitySectionManager.java:98) ~[client-1.18.1-20211210.034407-srg.jar%23121!/:?]
	at net.minecraft.world.level.entity.PersistentEntitySectionManager.addNewEntityWithoutEvent(PersistentEntitySectionManager.java:76) ~[client-1.18.1-20211210.034407-srg.jar%23121!/:?]
	at net.minecraft.server.level.ServerLevel.m_8853_(ServerLevel.java:827) ~[client-1.18.1-20211210.034407-srg.jar%23121!/:?]
	at net.minecraft.server.level.ServerLevel.m_8834_(ServerLevel.java:771) ~[client-1.18.1-20211210.034407-srg.jar%23121!/:?]
	at net.minecraft.server.players.PlayerList.m_11261_(PlayerList.java:190) ~[client-1.18.1-20211210.034407-srg.jar%23121!/:?]
	at net.minecraft.server.network.ServerLoginPacketListenerImpl.m_143699_(ServerLoginPacketListenerImpl.java:138) ~[client-1.18.1-20211210.034407-srg.jar%23121!/:?]
	at net.minecraft.server.network.ServerLoginPacketListenerImpl.m_10055_(ServerLoginPacketListenerImpl.java:125) ~[client-1.18.1-20211210.034407-srg.jar%23121!/:?]
	at net.minecraft.server.network.ServerLoginPacketListenerImpl.m_10050_(ServerLoginPacketListenerImpl.java:69) ~[client-1.18.1-20211210.034407-srg.jar%23121!/:?]
	at net.minecraft.network.Connection.m_129483_(Connection.java:229) ~[client-1.18.1-20211210.034407-srg.jar%23121!/:?]
	at net.minecraft.server.network.ServerConnectionListener.m_9721_(ServerConnectionListener.java:142) ~[client-1.18.1-20211210.034407-srg.jar%23121!/:?]
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:882) ~[client-1.18.1-20211210.034407-srg.jar%23121!/:?]
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:808) ~[client-1.18.1-20211210.034407-srg.jar%23121!/:?]
	at net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:86) ~[client-1.18.1-20211210.034407-srg.jar%23121!/:?]
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:668) ~[client-1.18.1-20211210.034407-srg.jar%23121!/:?]
	at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:258) ~[client-1.18.1-20211210.034407-srg.jar%23121!/:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
```

Let me know if you need more from the logs, this was the only error, and no other mods installed.  
I expect this to just be something incompatible with newer versions of Forge, it worked fine with earlier versions.

**Comment by p3lim** [comment]
It works fine in Forge 39.0.44, I found the change in Forge that causes this issue:
https://github.com/MinecraftForge/MinecraftForge/pull/8235

**Comment by DNewman5** [comment]
I got the same crash with Forge 39.0.55

**Comment by tcvwgli02** [comment]
same here 
I got the same crash with Forge 39.0.55

**Comment by Texas10mm** [comment]
I'm getting the same crash with 39.0.58

**Comment by MrSushy** [comment]
I'm getting the same crash with 39.0.57.
Mod Version: 1.18.1-1.5.1, same with 1.18.1-1.5.2

**Comment by HalcyonSeas73** [comment]
It sounds like this issue is related to Forge changes. You can probably downgrade to Forge 39.0.44 until the issue is fixed.

**Comment by morginatom** [comment]
I'm having the same issue in forge 39.0.63, placing a bloc and using it crash instantly (07/02) 23:40
singleplayer
1.18.1

**Comment by Lothrazar** [comment]
should be resolved along with similar issues, if not working on a 1.18.1-1.5.4 for this soon
