### ISSUE TITLE
Server Crashes when i am using Network

### ISSUE THREAD

**Issue by ollstar41** [PrinceOfAmber/Storage-Network#519]
Minecraft Version: 
1.19.2
Forge Version: 
43.3.0
Mod Version: 
1.7.0
Single Player or Server:
Server
Describe problem (what you were doing; what happened; what should have happened):
I am using network and in one moment it crashes server.

Log file link:
https://drive.google.com/file/d/1Vlo4yXUjUFOsa9fmaDyeK7nbFKcM0tnr/view?usp=sharing

Video/images/gifs (direct upload or link): 

None just logs

**Comment by UrbanSide** [comment]
I have this error too on 1.18.2 last mod version.
```
---- Minecraft Crash Report ----
// This doesn't make any sense!

Time: 9/26/23, 2:02 PM
Description: Ticking block entity

java.lang.NullPointerException: Cannot invoke "com.lothrazar.storagenetwork.api.DimPos.offset(net.minecraft.core.Direction)" because the return value of "com.lothrazar.storagenetwork.api.IConnectable.getPos()" is null
	at com.lothrazar.storagenetwork.capability.CapabilityConnectableLink.addToStackProviderBatch(CapabilityConnectableLink.java:292) ~[SimpleStorageNetwork-1.18.2-1.7.0.jar%23305!/:1.18.2-1.7.0] {re:classloading}
	at com.lothrazar.storagenetwork.block.main.NetworkModule.executeRequestBatch(NetworkModule.java:312) ~[SimpleStorageNetwork-1.18.2-1.7.0.jar%23305!/:1.18.2-1.7.0] {re:classloading}
	at com.lothrazar.storagenetwork.block.main.TileMain.executeRequestBatch(TileMain.java:76) ~[SimpleStorageNetwork-1.18.2-1.7.0.jar%23305!/:1.18.2-1.7.0] {re:classloading}
	at com.lothrazar.storagenetwork.block.main.TileMain.updateExports(TileMain.java:255) ~[SimpleStorageNetwork-1.18.2-1.7.0.jar%23305!/:1.18.2-1.7.0] {re:classloading}
	at com.lothrazar.storagenetwork.block.main.TileMain.tick(TileMain.java:274) ~[SimpleStorageNetwork-1.18.2-1.7.0.jar%23305!/:1.18.2-1.7.0] {re:classloading}
	at com.lothrazar.storagenetwork.block.main.TileMain.serverTick(TileMain.java:261) ~[SimpleStorageNetwork-1.18.2-1.7.0.jar%23305!/:1.18.2-1.7.0] {re:classloading}
	at net.minecraft.world.level.chunk.LevelChunk$BoundTickingBlockEntity.tick(LevelChunk.java:790) ~[server-1.18.2-20220404.173914-srg.jar%23366!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.level.chunk.LevelChunk$RebindableTickingBlockEntityWrapper.tick(LevelChunk.java:886) ~[server-1.18.2-20220404.173914-srg.jar%23366!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.level.Level.redirect$cbg000$redirectTick(Level.java:5889) ~[server-1.18.2-20220404.173914-srg.jar%23366!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:LevelMixin,pl:mixin:APP:antixray.mixins.json:LevelMixin,pl:mixin:APP:sliceanddice.mixins.json:LevelMixin,pl:mixin:APP:sereneseasons.mixins.json:MixinLevel,pl:mixin:APP:starlight.mixins.json:common.world.LevelMixin,pl:mixin:APP:valkyrienskies-common.mixins.json:feature.clip_replace.MixinLevel,pl:mixin:APP:valkyrienskies-common.mixins.json:feature.get_entities.MixinLevel,pl:mixin:APP:valkyrienskies-common.mixins.json:feature.world_border.MixinLevel,pl:mixin:APP:valkyrienskies-common.mixins.json:world.level.MixinLevel,pl:mixin:APP:observable.common.json:LevelMixin,pl:mixin:A}
	at net.minecraft.world.level.Level.tickBlockEntities(Level.java:714) ~[server-1.18.2-20220404.173914-srg.jar%23366!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:LevelMixin,pl:mixin:APP:antixray.mixins.json:LevelMixin,pl:mixin:APP:sliceanddice.mixins.json:LevelMixin,pl:mixin:APP:sereneseasons.mixins.json:MixinLevel,pl:mixin:APP:starlight.mixins.json:common.world.LevelMixin,pl:mixin:APP:valkyrienskies-common.mixins.json:feature.clip_replace.MixinLevel,pl:mixin:APP:valkyrienskies-common.mixins.json:feature.get_entities.MixinLevel,pl:mixin:APP:valkyrienskies-common.mixins.json:feature.world_border.MixinLevel,pl:mixin:APP:valkyrienskies-common.mixins.json:world.level.MixinLevel,pl:mixin:APP:observable.common.json:LevelMixin,pl:mixin:A}
	at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:350) ~[server-1.18.2-20220404.173914-srg.jar%23366!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:forgeendertech:coremod,xf:fml:sereneseasons:temperature_transformer,re:classloading,pl:accesstransformer:B,xf:fml:forgeendertech:coremod,xf:fml:sereneseasons:temperature_transformer,pl:mixin:APP:antixray.mixins.json:ServerLevelMixin,pl:mixin:APP:forge-sfcr-common.mixins.json:ServerWorldAccessor,pl:mixin:APP:supplementaries.mixins.json:ServerLevelMixin,pl:mixin:APP:botania_xplat.mixins.json:MixinServerLevel,pl:mixin:APP:the_bumblezone.mixins.json:world.ServerWorldMixin,pl:mixin:APP:krypton.mixins.json:server.fastchunkentityaccess.ServerWorldMixin,pl:mixin:APP:immersive_weathering-common.mixins.json:ServerLevelMixin,pl:mixin:APP:starlight.mixins.json:common.world.ServerWorldMixin,pl:mixin:APP:crafttweaker.mixins.json:common.transform.world.level.MixinServerLevel,pl:mixin:APP:immersiveengineering.mixins.json:coremods.ServerWorldMixin,pl:mixin:APP:cold_sweat.mixin.json:MixinBlockUpdate,pl:mixin:APP:byg.mixins.json:common.world.MixinServerLevel,pl:mixin:APP:mixins.layered_snowfall.json:ChunkTickMixin,pl:mixin:APP:valkyrienskies-common.mixins.json:feature.shipyard_entities.MixinServerLevel,pl:mixin:APP:valkyrienskies-common.mixins.json:server.world.MixinServerLevel,pl:mixin:APP:minerslung.mixins.json:ServerLevelBlockTracker,pl:mixin:APP:observable.common.json:ServerLevelMixin,pl:mixin:APP:alternate_current.mixins.json:ServerLevelMixin,pl:mixin:APP:betterdeserttemples.mixins.json:ServerLevelMixin,pl:mixin:APP:blueprint.mixins.json:ServerLevelMixin,pl:mixin:APP:friendsandfoes-common.mixins.json:ServerWorldAccessor,pl:mixin:APP:rottencreatures-common.mixins.json:common.ServerLevelMixin,pl:mixin:APP:assets/sound_physics_remastered/sound_physics_remastered.mixins.json:ServerWorldMixin,pl:mixin:APP:create.mixins.json:accessor.ServerLevelAccessor,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1239) ~[server-1.18.2-20220404.173914-srg.jar%23366!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:inject_resources.MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:flytre_lib.mixins.json:base.MinecraftServerMixin,pl:mixin:APP:flytre_lib.mixins.json:config.MinecraftServerMixin,pl:mixin:APP:fastload.mixins.json:server.MinecraftServerMixin,pl:mixin:APP:crafttweaker.mixins.json:common.access.server.AccessMinecraftServer,pl:mixin:APP:byg.mixins.json:access.MinecraftServerAccess,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:APP:valkyrienskies-common.mixins.json:server.MixinMinecraftServer,pl:mixin:A}
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:424) ~[server-1.18.2-20220404.173914-srg.jar%23366!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:blueprint.mixins.json:DedicatedServerMixin,pl:mixin:APP:tombstone.mixins.json:DedicatedServerMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1156) ~[server-1.18.2-20220404.173914-srg.jar%23366!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:inject_resources.MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:flytre_lib.mixins.json:base.MinecraftServerMixin,pl:mixin:APP:flytre_lib.mixins.json:config.MinecraftServerMixin,pl:mixin:APP:fastload.mixins.json:server.MinecraftServerMixin,pl:mixin:APP:crafttweaker.mixins.json:common.access.server.AccessMinecraftServer,pl:mixin:APP:byg.mixins.json:access.MinecraftServerAccess,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:APP:valkyrienskies-common.mixins.json:server.MixinMinecraftServer,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:954) ~[server-1.18.2-20220404.173914-srg.jar%23366!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:inject_resources.MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:flytre_lib.mixins.json:base.MinecraftServerMixin,pl:mixin:APP:flytre_lib.mixins.json:config.MinecraftServerMixin,pl:mixin:APP:fastload.mixins.json:server.MinecraftServerMixin,pl:mixin:APP:crafttweaker.mixins.json:common.access.server.AccessMinecraftServer,pl:mixin:APP:byg.mixins.json:access.MinecraftServerAccess,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:APP:valkyrienskies-common.mixins.json:server.MixinMinecraftServer,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.lambda$spin$2(MinecraftServer.java:263) ~[server-1.18.2-20220404.173914-srg.jar%23366!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:inject_resources.MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:flytre_lib.mixins.json:base.MinecraftServerMixin,pl:mixin:APP:flytre_lib.mixins.json:config.MinecraftServerMixin,pl:mixin:APP:fastload.mixins.json:server.MinecraftServerMixin,pl:mixin:APP:crafttweaker.mixins.json:common.access.server.AccessMinecraftServer,pl:mixin:APP:byg.mixins.json:access.MinecraftServerAccess,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:APP:valkyrienskies-common.mixins.json:server.MixinMinecraftServer,pl:mixin:A}
	at java.lang.Thread.run(Thread.java:833) [?:?] {re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------
```

**Comment by mbainter** [comment]
I have seen this as well in 1.19.  In our case, it seemed to be triggered when a player tried to connect two chests with a single link cable.
