### ISSUE TITLE
JEI builds 214 & 215 cause NPE

### ISSUE THREAD

**Issue by kreezxil** [PrinceOfAmber/Storage-Network#91]
updated my pack World of Dragons to Forge 2750, now when a player uses the Simple Storage Network in any fashion they crash out.

Client Crash Reports:

- https://pastebin.com/BWzQcv6c
- https://pastebin.com/NNRK3gLq
I've got 100's more, I'll roll forge down a version till i get a working version. or up.

**Comment by kreezxil** [comment]
It is not Forge at all. As I rolled all the way down to 2732 and it continued to crash in this way. It must be one of the mods I added last to my pack. I'm testing now removing them in the order I added them. Thankfully I do changelogs. :)

**Comment by kreezxil** [comment]
ok, not that at all, apparently people are reporting problems. Looks like JEI is at fault. Ok, the problem is introduced in JEI 1.12.2-4.12.0.214 and continues into build 215. I'll post this on JEI forums. Rolling down to build 213 solves the issue.

**Comment by LemADEC** [comment]
The actual crash is
```
java.util.concurrent.ExecutionException: java.lang.NoSuchMethodError: mezz.jei.runtime.JeiRuntime.getItemListOverlay()Lmezz/jei/gui/overlay/IngredientListOverlay;
    at java.util.concurrent.FutureTask.report(Unknown Source)
    at java.util.concurrent.FutureTask.get(Unknown Source)
    at net.minecraft.util.Util.runTask(SourceFile:531)
    at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1087)
    at net.minecraft.client.Minecraft.run(Minecraft.java:3940)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.NoSuchMethodError: mezz.jei.runtime.JeiRuntime.getItemListOverlay()Lmezz/jei/gui/overlay/IngredientListOverlay;
    at mrriegel.storagenetwork.jei.JeiHooks.getJeiTextInternal(JeiHooks.java:39)
    at mrriegel.storagenetwork.jei.JeiHooks.getFilterText(JeiHooks.java:10)
    at mrriegel.storagenetwork.gui.GuiContainerStorageInventory.initGui(GuiContainerStorageInventory.java:78)
    at mrriegel.storagenetwork.request.GuiRequest.initGui(GuiRequest.java:21)
    at net.minecraft.client.gui.GuiScreen.setWorldAndResolution(GuiScreen.java:478)
    at net.minecraft.client.Minecraft.displayGuiScreen(Minecraft.java:1017)
    at net.minecraftforge.fml.client.FMLClientHandler.showGuiScreen(FMLClientHandler.java:501)
    at net.minecraftforge.fml.common.FMLCommonHandler.showGuiScreen(FMLCommonHandler.java:321)
    at net.minecraftforge.fml.common.network.internal.FMLNetworkHandler.openGui(FMLNetworkHandler.java:112)
    at net.minecraft.entity.player.EntityPlayer.openGui(EntityPlayer.java:2550)
    at net.minecraftforge.fml.common.network.internal.OpenGuiHandler.process(OpenGuiHandler.java:50)
    at net.minecraftforge.fml.common.network.internal.OpenGuiHandler.lambda$channelRead0$0(OpenGuiHandler.java:43)
    at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
    at java.util.concurrent.FutureTask.run(Unknown Source)
    at net.minecraft.util.Util.runTask(SourceFile:529)
    ... 9 more
```

**Comment by PrinceOfAmber** [comment]
This doesn thappen for me with ONLY storage network installed, but in my other world I added FastWorkbench and a few others and I got almost the exact same thing https://paste.dimdev.org/oxogezadip.mccrash

**Comment by PrinceOfAmber** [comment]
Yep thanks for  all the replies 
I get a crash on JEI 0.215

works on 0.212

I assume this is a JEI bug that will get fixed.
If its NOT a JEI bug, then their API has changed and i need to update, but i need to wait a while to see what they do.
If JEI doesnt get changed and their API is new and different i will update to storage 1.3.0 to work on  this changed version (later down the road)

**Comment by PrinceOfAmber** [comment]
@LemADEC  your crash looks like a different one, log claims it cant find JEI at all.

Storage should work with JEI not installed just fine, if its installed then minimum JEI is =4.10.0.199

**Comment by LemADEC** [comment]
@PrinceOfAmber yes, the call stacks are different and for a good reason: the crash reported by #91 (here) is reproduced right after the one reported in #88. The former is the one reported in the launcher, the later is the actual trigger.
